### ISSUE TITLE
Send task with "DOING" leads to misformed task in Todoist and Logseq

### ISSUE THREAD

**Issue by P1Rebo** [hkgnp/logseq-todoist-plugin#38] opened 2022-07-01 07:15 UTC
If I try to send a task that has "DOING" in the line, the task name gets corrupt.
See attached example!
[image](https://user-images.githubusercontent.com/17112602/176844046-00be12ec-72dd-4e8f-b03b-f8c588a5c724.jpeg)

**Comment by hkgnp** [comment] 2022-07-02 09:20
Hi I don't seem to have this problem. 
Does this happen consistently for you?

**Comment by P1Rebo** [comment] 2022-07-02 09:21
Yes, happens when I start the line with DOING ...

**Comment by hkgnp** [comment] 2022-07-02 09:23
Hmm, doesn't happen for me though.
<img width="353" alt="Screenshot 2022-07-02 at 5 23 43 PM" src="https://user-images.githubusercontent.com/47936793/176994648-ed493e4e-6284-4086-9804-951e3659801f.png">

**Comment by P1Rebo** [comment] 2022-07-02 13:55
Ok, I'll check later and write some infos. Maybe my settings?

**Comment by P1Rebo** [comment] 2022-07-02 21:08
Here is how I can reproduce.

![image](https://user-images.githubusercontent.com/17112602/177016197-debe7f25-1118-41f4-b48d-73060a400943.jpeg)

Settings (removed api token)

{
  "apiToken": "xxx",
  "pullDefaultProject": "---",
  "pullDefaultAppend": true,
  "addParentBlock": "false",
  "clearTasks": true,
  "sendDefaultProject": "Inbox (2275143673)",
  "sendDefaultDeadline": false,
  "sendDefaultLabel": "",
  "appendLogseqUri": "Link title",
  "appendTodoistUrl": "Link content",
  "disabled": false
}

**Comment by P1Rebo** [comment] 2022-07-10 14:42
@hkgnp any updates here?

**Comment by hkgnp** [comment] 2022-07-16 04:14
Hi I am still not able to reproduce your issue though.

**Comment by hkgnp** [comment] 2022-12-19 03:16
Should be fixed in v5.1.1. Please re-open the issue if the problem persists.

**Closed by hkgnp** 2022-12-19 03:16 UTC
