### ISSUE TITLE
How to keep syncing between todoist and logseq ?

### ISSUE THREAD

**Issue by haoadoreorange** [hkgnp/logseq-todoist-plugin#43] opened 2022-08-05 13:40 UTC
Hi,

First I'm sorry if this is not the place for the question.

I've been struggling a bit to adapt the plugin for my use case. Is it possible to 2-way sync between the 2 tools ?

For example if I'm assigned a task in todoist, I can pull the task to logseq (without removing it in todoist), and then add some notes in logseq, these new notes would then be added on todoist side. I know that the sync is not automatic, but is it possible to even do it manually ? Like pushing to an already existing task in todoist.

**Comment by sandrofsousa** [comment] 2022-08-09 07:46
Kudos to the developers, the plugin idea is awesome. Tough, I'm struggling with the use case as well, a two-way sync would fit a broader use case and make tasks more manageable. Unfortunately, I can't help developing that myself but perhaps the developers can take inspiration from Raycast implementation [here](https://github.com/raycast/extensions/tree/d2cae3a2f1377968944ffbec9082c724541f70f9/extensions/todoist/).

**Comment by hkgnp** [comment] 2023-09-04 00:13
Duplicate of #29.

**Closed by hkgnp** 2023-09-04 00:13 UTC
Labels: duplicate
