### ISSUE TITLE
Feature Request: "todoist - send task" includes Backlink (deep link) to Logseq page and vice versa

### ISSUE THREAD

**Issue by P1Rebo** [hkgnp/logseq-todoist-plugin#24] opened 2022-05-09 20:34 UTC
Thanks again @hkgnp for this great plugin! I'm heavily using it.

Since Logseq introduced the feature of Page URLs (deeplinks) it would be cool if possible to send a task to todoist and by default this todoist task is a markdown link that links back to the original page URL. Same goes for the Todo inside Logseq, it would be cool if it would include the Link to the Todo within Todoist (or even sync the state).

Example
I've a logseq page that is a project description, e.g. "my new house". As part of this project I've a todo list, e.g. next steps.
This list containts todos that I have send to Todoist.

When working with Todoist I want to be able to quickly open the project information page within Logseq. So therefore the complete todo header would be a link to this specific project page within Logseq.

When working with Logseq I want to be able to jump to the todoist task in order to see the status over there. Even better would be, if the Plugin could synchronize the states between Logseq and Todoist, but I guess this is more difficult.

Would be very helpful to at least be able to configure this behaviour.

Thanks a lot in advance!

Best, p1rebo

**Comment by hkgnp** [comment] 2022-05-17 03:23
Let me look into this.

**Comment by P1Rebo** [comment] 2022-05-17 06:59
Thanks! Meanwhile I got you a fresh brewed coffee ;-)

**Comment by P1Rebo** [comment] 2022-05-17 16:00
Sure, links can be inserted with Markdown style text. so => [Hypertext](https://todoist.com/)
See reference here: https://todoist.com/help/articles/text-formatting

**Comment by P1Rebo** [comment] 2022-05-18 04:45
I tested it. Without "DOING" in the beginning it works. With "DOING" it seems to create a log message.
Furthermore, is there a way to avoid the popup window, e.g. by setting default values?
I'd prefer to have always priority 4 + inbox since I review the complete todoist tasks afterwards and prioritize then.

**Comment by hkgnp** [comment] 2022-05-18 07:17
Hi, I will look into removing the prefixes.

As for setting defaults, let me think about them as previously the feedback I received was that defaults are not preferred, and users preferred to just set it as per the task.

**Comment by P1Rebo** [comment] 2022-05-18 07:29
Ok thanks! It really depends on the user habit I guess. I prefer to avoid mouse actions :-)
Maybe there is a good way to make this configurable, and by default to have this popup with each task.
You are the master :-)

**Comment by hkgnp** [comment] 2022-05-20 05:33
> Ok thanks! It really depends on the user habit I guess. I prefer to avoid mouse actions :-) Maybe there is a good way to make this configurable, and by default to have this popup with each task. You are the master :-)

Implemented in v4.1.8.

**Comment by P1Rebo** [comment] 2022-05-23 09:15
Hi @hkgnp, the behaviour without the popup is perfect now.
Still I have the issue that the todoist task will be modified using a newline which breaks the todo.
See example.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/17112602/169786158-c3369aa0-6796-4f46-b69f-e71d3ff6aee3.png">



Furthermore "DOING" is not been deleted on Logseq side, on todoist side the text is corrupted.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/17112602/169786423-f87062ab-b166-4859-8e33-b7f208bdcd90.png">

"TODO" is not removed on Logseq side, but in todoist.

Should I open a new issue?

**Comment by hkgnp** [comment] 2022-05-24 04:05
Could you try with v4.2.1?

**Comment by P1Rebo** [comment] 2022-05-24 07:18
Sure. I tried but unfortunately I get the same result...
<img width="271" alt="2022-05-24_09h17_12" src="https://user-images.githubusercontent.com/17112602/169971824-c0f60675-dc0c-48c4-b6a3-008d460ca646.png">
<img width="271" alt="2022-05-24_09h17_12" src="https://user-images.githubusercontent.com/17112602/169971933-806f4acd-b733-44b0-9ba5-ef57fed930e1.png">

**Comment by hkgnp** [comment] 2022-05-24 07:25
Are you on markdown or org mode?

**Comment by P1Rebo** [comment] 2022-06-05 21:04
Hey @hkgnp, any updates here?

**Comment by hkgnp** [comment] 2022-06-05 23:12
Hi, sorry, I still am not able to reproduce the issue. It works fine on my side. 
Do you mind copying your specific markdown block that doesn't work so I can test it out?

**Comment by TomazWang** [comment] 2022-06-08 16:41
Hi @hkgnp,

I can reproduce the backlink issue mention by @P1Rebo in [this comment](https://github.com/hkgnp/logseq-todoist-plugin/issues/24#issuecomment-1135501627) (the second half: "This is a second test ..."). I found that in `removePrefixWhenAddingTodoistUrl` function, non-task blocks are not getting `[]` syntax attached. [This PR](https://github.com/hkgnp/logseq-todoist-plugin/pull/32) might be a solution for this. Please check it out, thanks.

**Comment by hkgnp** [comment] 2022-06-12 04:33
Thanks for the PR. Have merged it! Will cut a release soon!

**Closed by hkgnp** 2022-06-12 04:33 UTC
